# Use the official Ruby image
FROM ruby:3.3

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Set the working directory
WORKDIR /rails

# Copy the Gemfile and Gemfile.lock
COPY Gemfile* ./

# Install gems
RUN bundle install

# Copy the rest of the application code
COPY . .

# Expose port 3010 to the outside world
EXPOSE 3010

ENTRYPOINT [ "/rails/bin/docker-entrypoint" ]

# Start the Rails server
CMD ["./bin/rails", "server"]
