version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres -c 'max_connections=500'"
    ports:
      - "5432:5432"
    networks:
      - app-network
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: './bin/rails server'
    volumes:
      - app-storage:/rails/storage
    ports:
      - "3010:3000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS}
volumes:
  postgres_data:
  app-storage:

networks:
  app-network:
